export type {
  Product,
  SKU,
  Warehouse,
  InventoryMovement,
  UnitOfMeasure,
  Dimensions,
  WarehouseType,
  MovementType,
  ProductCreateInput,
  ProductPatchInput,
  WarehouseCreateInput,
  WarehousePatchInput,
  StockMovementInput,
  StockAvailability,
} from "./types.js";
